config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friends
  resources :contacts, only: [:new, :create]
 
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "search",to:'friends#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "asolabofficial@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord

  #validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:github, :google_oauth2]

         has_many :friends 

     

         
        
         def self.from_omniauth(access_token)
    user = User.where(email: access_token.info.email).first
    unless user
         user = User.create(
            email: access_token.info.email,
            password: Devise.friendly_token[0,20]
         )
     end
     user.name = access_token.info.name
     user.image = access_token.info.image
     user.uid = access_token.uid
     user.provider = access_token.provider
     user.skip_confirmation!
     user.save!
     user
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /friends or /friends.json
  def index 
    @q = Friend.ransack(params[:q])
    @friends = @q.result(distinct: true)
  end



 
  

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
    
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
      @friend  = current_user.friends.build(friend_params)
      respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity } 
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friends = Friend.find(params[:id])
    @friend.destroy


    respond_to do |format|

      format.js
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit This Profile" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb:

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

def google_oauth2

  handle_auth "Google"
  
  end

  def github

    handle_auth "Github"
      
  end

  def handle_auth(kind)
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.auth_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>
<div> <center>  <%= link_to 'Homepage', root_path, class:"btn btn-dark btn-sm"; %>  <br> </center> </div>
   

app/views/contacts/new.html.erb
<title>Contact Form </title>
 
  <body>
  

  <div class="content">
    
    <div class="container">
      <div class="row align-items-stretch no-gutters contact-wrap">
        <div class="col-md-12">
          <div class="form h-100">

            <h3>Send us a message</h3>
            
              <div class="row">

                <%= form_for @contact, auto_html5_validation: false do |f| %>
                <div class="col-md-8 form-group mb-5">
                  <%= f.label :name, class: "col-form-label" %></br>
                  <%= f.text_field :name, required: true, class: "col-md-6 contact-form-text-area", placeholder: "Your Name" %></br>
                 
                </div>
                <div class="col-md-6 form-group mb-5">
                  
                  <%= f.label :email, class: "col-form-label" %></br>
                  <%= f.text_field :email, required: true, pattern: '[^@]+@[^@]+\.[a-zA-Z]{2,6}', class: "col-md-8 contact-form-text-area", placeholder: "#sendgrid use aso@hausasports.art as your email" %></br>
                  
                </div>
              </div>

          

              <div class="row">
                <div class="col-md-12 form-group mb-5">
              
                  <%= f.label :message, class: "col-form-label" %></br>
                   <%= f.text_area :message, rows: 8, cols: 80, required: true, class: "contact-form-text-area", 
            placeholder: "Write your message here, remember to include your email in your mail 😊, Thanks! "%></br>
                </div>
              </div>

              <div class= "d-none">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>
              
              <div class="row">
            <%= f.submit 'Send Message', class: 'btn btn-primary' %>
              </div>
           
              <% end %>

          </div>
        </div>
       
             
          </div>
        </div>
      </div>
    </div>

  </div>
    
    



  </body>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
         <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" >
    
   
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name", :required => true;%>
  </div>

  <div class="mb-3">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name", :required => true;  %>
  </div>

  <div class="mb-3">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email", :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'; %>
  </div>

  <div class="mb-3">
   
    <%= form.text_field :phone, class:"form-control", placeholder:"phone", :required => true; %>
  </div>

  <div class="mb-3">
   
    <%= form.text_field :twitter, class:"form-control", placeholder:"twitter", :required => true;%>
  </div>
<div class="mb-3">
   
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type:"hidden"%>
  </div>
    
    <div>
    <br>
    <%= form.submit  class:"btn btn-success", :onclick => "return confirm('UPDATE FRIEND?')"  ;%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%=  turbo_frame_tag dom_id friend %>">

	
 

</div>

app/views/friends/edit.html.erb
<h1>Update friend</h1>



<%= render "form", friend: @friend %>

<br>


  <div style="width:130px; margin-top: -10px" >
  <%= button_to "Delete this friend", @friend, method: :delete, :onclick => "return confirm('DELETE ACCOUNT?')",  class:"btn btn-outline-danger btn-sm", role:"button";%></div>

<div style="width:130px;margin-left: 140px;margin-top: -30px">
  <%= button_to "Back to friends", friends_path, class:"btn btn-outline-dark btn-sm";%>
  </div>
  

app/views/friends/index.html.erb
<% if user_signed_in? %>
<h1>Friends</h1>
        <%= search_form_for @q do |f| %> 
  <div>  <%= f.search_field :first_name_or_last_name_or_email_or_phone_or_twitter_cont, placeholder:"Search for Your Details", class: "col-lg-3";%></div>
<div style="width:130px;margin-left: 320px;margin-top: -30px"><%= f.submit class:"btn btn-outline-success btn-sm";%></div>

<% end %>
    <br>

<div id="friends">
    
   <div>
    <table class="table table-hover ">
  <thead class="table-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">Name </th>
      <th scope="col">Email </th>
      <th scope="col">Phone </th>
      <th scope="col">Twitter </th>
      
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
  <tr>
      <td scope="row"></td>
      <td> <%= link_to friend.first_name.capitalize + " " + friend.last_name.capitalize, friend, style:"text-decoration: none;"%></td>
      <td><%= friend.email.capitalize %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
     
      <td><%= button_to "Destroy this friend", friend, method: :delete,  class:"btn btn-outline-danger btn-md",  :onclick => "return confirm('DELETE ACCOUNT?')";%></td>
      

      
 
      </tr>
   <% end %>
   <% end %>
    </tbody>
  </table>
  </div>
    


</div>


<% else %>

<h1>Hello World! </h1>
<p>Welcome to Asolab Ruby!</p>
<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>
<br>

<%= render "form", friend: @friend %>

<br>

<div style="width:130px;margin-left: 140px;margin-top: -60px">
  <%= link_to "Back   Friends", friends_path, class:"btn btn-primary";  %>
</div>

app/views/friends/search.html.erb
<h1>Search Result</h1>

<% render friend: @friend %> 

app/views/friends/show.html.erb
<div class="text-light bg-dark p-5 rounded-sm m-5">
  <%= turbo_frame_tag "friend", data: { turbo: false } do %> 
  <%= image_tag current_user.image, size: '50x50' if current_user.image?  %>
  <%= current_user.name %>
  <h1 class="display-4"><strong>Hello,</strong> <%=@friend.first_name.capitalize! %> <%= @friend.last_name.capitalize!  %></h1>
  <p class="lead"><%= @friend.email.capitalize %></p>
  <hr class="my-4">
  <p><%= @friend.twitter.capitalize %>        <strong>|</strong>        <%= @friend.phone %></p>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-primary btn-sm"; %>
  </div>
   <% end %>  
<div style="width:130px;margin-left: 50px;"><%= link_to "Back to friends", friends_path, class:"btn btn-dark btn-sm";%></div>
  
<div style="width:130px;margin-left: 180px;margin-top: -30px" > <%= button_to "Delete Account", @friend, method: :delete, class:"btn btn-danger btn-sm", 
 :onclick => "return confirm('DELETE ACCOUNT?')";%>
 
 
</div> 




    </div>
  </div>
</div>     



 
  

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me- mb-2    mb-lg-0">
        <li class="nav-item btn-group">
          
          <%= link_to 'Add Friend', new_friend_path, class:"navbar-si btn btn-dark", style:"text-decoration: none;"%>
          <% if user_signed_in? %>
          <%= image_tag current_user.image, size: '50x50' if current_user.image? %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete,  class:"navbar-si btn btn-dark", style:"text-decoration:none;"%>
         
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"navbar-si btn btn-dark", style:"text-decoration: none;"%>
         <% else %>
          <%= link_to 'Sign In', new_user_session_path, class:"navbar-si btn btn-dark", style:"text-decoration: none;"%>
           <%= link_to 'Sign Up', new_user_registration_path, class:"navbar-si btn btn-dark", style:"text-decoration: none;"%>
          <% end %>
           <%= link_to 'About Us', home_about_path, class:"navbar-sidet btn btn-dark", style:"text-decoration: none;"%>
         </li>
        </div>
      <!--<form class="d-flex " role="search" method="GET" action="/Search">
        <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>

      </form>-->
  </div>
</nav>

app/views/home/about.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    
    <!-- Style -->
    <link rel="stylesheet" href="css/style.css">

    <title>Contact Form #7</title>
  </head>
  <body>
  

  <div class="content">
    
    <div class="container">
      <div class="row align-items-stretch no-gutters contact-wrap">
        <div class="col-md-8">
          <div class="form h-100">

            <h3>Our Mission and Vision</h3>
            
              
          </div>
        </div>
        <div class="col-md-4">
          <div class="contact-info h-100">
            <h3>Contact Information</h3>
            <p class="mb-5"><h5>Friends List Application developed by asolab to have all your contacts at your fingertips.....</h5></p>
            <ul class="list-unstyled">
              <li class="d-flex">
                <span class="wrap-icon icon-room mr-3"></span>
                <span class="text">Lagos, Nigeria.</span>
              </li>
              <li class="d-flex">
                <span class="wrap-icon icon-phone mr-3"></span>
                <span class="text">+234 70 6376 6148</span>
              </li>
              <li class="d-flex">
                <span class="wrap-icon icon-envelope mr-3"></span>
                <span class="text">asolabofficial@gmail.com</span>
                <li class="d-flex">
                <span class="wrap-icon icon-envelope mr-3"></span>
                <span class="text"><%= link_to 'Message Us', new_contact_path, class:"btn btn-primary"%></span>
                
                
                  
             
                
            
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
    
    


  </body>
</html>

app/views/home/index.html.erb
<h1>Hello World! </h1>
<p>Asolab Ruby!</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close pull-right" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags  %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.rtl.min.css" integrity="sha384-+4j30LffJ4tgIMrq9CwHvn0NjEvmuDCOfk6Rpg2xg7zgOxWWtLtozDEEVvBPgHqE" crossorigin="anonymous">


    <title>Our Friends App</title>
  </head>
  <body>

    <%= render 'home/header' %>
        <div class= "container">
          <% if notice %>
          <%= render "layouts/alert" %>
          <% end %>
        </br>

        <div class="alert alert-danger">
        <p class= 'alert'><%= alert %></p>
       
      

  
  <% flash.each do |key, message| %>
    <p class="alert alert-<%= key %>"><%= message %></p>
  <% end %>

          <%= yield %>
         

      
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    
  </body>
</html>